/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resumeBuilder.GUI;

import resumeBuilder.storage.Resume;
import resumeBuilder.storage.sections.PersonalInfo;
import javax.swing.JScrollPane;


/**
 *
 * @author tycook1
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public HomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        createAResumeButton = new javax.swing.JButton();
        editAnExistingResumeButton = new javax.swing.JButton();
        modifyPersonalInfoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createAResumeButton.setText("Create a resume");
        createAResumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAResumeButtonActionPerformed(evt);
            }
        });

        editAnExistingResumeButton.setText("Edit an existing resume");
        editAnExistingResumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAnExistingResumeButtonActionPerformed(evt);
            }
        });

        modifyPersonalInfoButton.setText("Modify personal info");
        modifyPersonalInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyPersonalInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(createAResumeButton)
                    .addComponent(editAnExistingResumeButton)
                    .addComponent(modifyPersonalInfoButton))
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(createAResumeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editAnExistingResumeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifyPersonalInfoButton)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void createAResumeButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	Resume defaultResume = new Resume("Resume Title");
        ResumeWizard c = new ResumeWizard(defaultResume);
        c.setVisible(true);
        
        dispose();
    }                                                   

    private void editAnExistingResumeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        ExistingResumePicker editExistingResumePicker = new ExistingResumePicker();
        editExistingResumePicker.setVisible(true);
    }                                                          

    private void modifyPersonalInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	// Either will be a personalinfo object with default values or with real values
    	PersonalInfo personalInfo = PersonalInfo.load();
        ModifyPersonalInfoScreen modifyPersonalInfoScreen = new ModifyPersonalInfoScreen(personalInfo);
        modifyPersonalInfoScreen.setVisible(true);
    }                                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton createAResumeButton;
    private javax.swing.JButton editAnExistingResumeButton;
    private javax.swing.JButton modifyPersonalInfoButton;
    // End of variables declaration                   
}
